### ISSUE TITLE
Standard PCA Folder Structure

### ISSUE THREAD

**Issue by BenBreaksThings** [cisagov/pca-gophish-composition-packer#52]
# 💡 Summary #

Standard folder structure to PCA GoPhish composition.

## Motivation and context ##

Each of the PCA assessments in the COOL currently have operators manually recreate the exact same folder structure in each assessment. However, automation is limited in that operators often differ in folder creation (e.g., use/mission of hyphens).

This would be useful as it would enable further scripting to navigate known locations, place/read files, and expedite infrastructure setup for operators as the new fiscal year will quintuple number of assessments year over year, automation and standardization is a critical enabler.

## Implementation notes ##

Folders needing to be created for every assessment at creation of the image:

/home/vnc/PCA
/home/vnc/PCA/Level-1
/home/vnc/PCA/Level-1/Data
/home/vnc/PCA/Level-2
/home/vnc/PCA/Level-2/Data
/home/vnc/PCA/Level-3
/home/vnc/PCA/Level-3/Data
/home/vnc/PCA/Level-4
/home/vnc/PCA/Level-4/Data
/home/vnc/PCA/Level-5
/home/vnc/PCA/Level-5/Data
/home/vnc/PCA/Level-6
/home/vnc/PCA/Level-6/Data
/home/vnc/PCA/Email_Templates
/home/vnc/PCA/Email_Targets

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Each of the listed folders is generated when a new environment is created

**Comment by dav3r** [comment]
@BenBreaksThings - Are any of the directories above intended to be used to interact with our Dockerized Gophish using the [gophish-tools helper scripts](https://github.com/cisagov/pca-gophish-composition/tree/develop/gophish-tools) (e.g. either importing or exporting files)?  If so, please let us know which ones- they will need to be given appropriate UNIX-level permissions, like what we did [here](https://github.com/cisagov/cool-assessment-terraform/blob/5912821b171450245b8ccd8ecc8e6211cc081a24/cloud-init/gophish-dir-setup.tpl.yml#L3-L10), so that the Gophish Docker container can read/write in those directories.

If not, I'd like to propose adding an additional standard directory that operators can use for general Gophish import/export purposes, maybe something along the lines of `/home/vnc/PCA/gophish-io`.

CC: @JCantu248, @nickviola, @ameliav

**Comment by BenBreaksThings** [comment]
I believe it will only need to interact with 2:

- /home/vnc/PCA/Email_Templates
- /home/vnc/PCA/Email_Targets

**Comment by dav3r** [comment]
> I believe it will only need to interact with 2:
> 
> * /home/vnc/PCA/Email_Templates
> * /home/vnc/PCA/Email_Targets

Which [gophish-tools helper scripts](https://github.com/cisagov/pca-gophish-composition/tree/develop/gophish-tools) need to interact with those directories?  Or is it a new script that still is in development?

What do you think about my idea for a general `/home/vnc/PCA/gophish-io` directory?

**Comment by BenBreaksThings** [comment]
the gophish-io option is okay to fight the battle of that permissions blocker, but for the purposes of processes it creates a litany of new issues for operations. One of those instances where engineering solutions do not align with how the operators will interact with it.

For example, the template folder referenced above gets used by Nick's setup script to pull in a template (or will in real campaigns, in his testing he has been operating out of a folder operators will not use). And the target list, who is receiving the phishes, is stored in the Email_Targets folder during infrastructure setup & testing after initial spin up.

**Comment by dav3r** [comment]
Understood (I think)- you'd like `/home/vnc/PCA/Email_Templates` and `/home/vnc/PCA/Email_Targets` to be the only two directories where the `gophish` container can write data to the host filesystem.  Is that correct?

**Comment by BenBreaksThings** [comment]
For the purposes of this ticket, those are the only two directories that I, personally, have a vested interest in that container interacting with from the list of folders above. I am not prepared to speak to permissions/other folders that @nickviola may be relying on.

**Comment by dav3r** [comment]
@nickviola - Please let us know if you need any other directories in the list above (besides the two mentioned by @BenBreaksThings) to be able to written to from the `gophish` container.  

If you have any other standard PCA directories that need to be added to our image, this is the place to mention it.
