### ISSUE TITLE
Why does this repo use a different owner for the Debian base AMI?

### ISSUE THREAD

**Issue by jsf9k** [cisagov/pca-gophish-composition-packer#78]
# 🐛 Summary #

I noticed that this repo uses the owner ID `903794441882` for the Debian Bullseye base AMI, while our other repos that use this base AMI use the owner ID `136693071363`.  (See [here](https://github.com/cisagov/debian-packer/blob/c025030ec998b6aff6a6d4a9b95bba2eb6045b7c/src/packer.json#L39), for example.)  Why is this so?

If there is no good reason for using a different base AMI for this particular repo then we should be consistent.

**Comment by dav3r** [comment]
See issue #56 for the background on this.  It seems that we closed that issue after https://github.com/cisagov/skeleton-packer/pull/83 was merged, but never actually reverted the owner ID back to `136693071363` for this repo.

@jsf9k, @mcdonnnj I'm fine with changing the owner ID back to `136693071363` as part of PR #77 if you are.

**Comment by jsf9k** [comment]
> @jsf9k, @mcdonnnj I'm fine with changing the owner ID back to `136693071363` as part of PR #77 if you are.

I'd prefer a separate PR but will accept @mcdonnnj's tie-breaking decision.

**Comment by dav3r** [comment]
OK, I'm fine with a separate PR for this.
